---

- name: Install server packages
  ansible.builtin.yum:
    name:
    - bind
    state: present
    update_cache: true

- name: Copy transferkey
  ansible.builtin.copy:
    src: files/named.zonetransfer.key
    dest: /etc/named.zonetransfer.key
    owner: root
    group: named
    mode: 0644

- name: Create resolv.conf to the servers
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: Set /etc/named permissions
  ansible.builtin.file:
    path: /etc/named
    owner: root
    group: named
    mode: 0670