{
 "title": "Summary",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job:",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "host",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_time_seconds{instance=\"$host\",job=\"$job\"} - node_boot_time_seconds{instance=\"$host\",job=\"$job\"}) or (time() - node_boot_time_seconds{instance=\"$host\",job=\"$job\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$host\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$host\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$host\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$host\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"$host\",mode=\"iowait\"}[2m])) * 100"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (instance) (avg_over_time(node_memory_MemFree_bytes{job=\"$job\", instance=\"$host\"}[10s]) or avg_over_time(node_memory_MemFree_bytes{job=\"$job\", instance=\"$host\"}[5m]))",
     "legendFormat": "Free"
    },
    {
     "expr": "avg by (instance) (avg_over_time(node_memory_Buffers_bytes{job=\"$job\", instance=\"$host\"}[10s]) or avg_over_time(node_memory_Buffers_bytes{job=\"$job\", instance=\"$host\"}[5m]))",
     "legendFormat": "Buffers"
    },
    {
     "expr": "clamp_min(avg by (instance) (((avg_over_time(node_memory_MemTotal_bytes{job=\"$job\", instance=\"$host\"}[10s]) or avg_over_time(node_memory_MemTotal_bytes{job=\"$job\", instance=\"$host\"}[5m])) - ((avg_over_time(node_memory_MemFree_bytes{job=\"$job\", instance=\"$host\"}[10s]) or avg_over_time(node_memory_MemFree_bytes{job=\"$job\", instance=\"$host\"}[5m]))+ \n(avg_over_time(node_memory_Buffers_bytes{job=\"$job\", instance=\"$host\"}[10s]) or avg_over_time(node_memory_Buffers_bytes{job=\"$job\", instance=\"$host\"}[5m])) + \n(avg_over_time(node_memory_Cached_bytes{job=\"$job\", instance=\"$host\"}[10s]) or avg_over_time(node_memory_Cached_bytes{job=\"$job\", instance=\"$host\"}[5m]))))),0)",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (instance) (avg_over_time(node_memory_MemTotal_bytes{job=\"$job\", instance=\"$host\"}[10s]) or avg_over_time(node_memory_MemTotal_bytes{job=\"$job\", instance=\"$host\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg by (instance) (avg(avg_over_time(node_memory_Cached_bytes{job=\"$job\", instance=\"$host\"}[10s]) or avg_over_time(node_memory_Cached_bytes{job=\"$job\", instance=\"$host\"}[5m])) without (job))",
     "legendFormat": "Cache"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$host\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$host\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - Writes"
    }
   ]
  },
  {
   "title": "Avalable space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$host\",job=\"$job\",device!~'rootfs',mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Network Traffic In",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{instance=\"$host\", job=\"$job\", device!=\"lo\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Out",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{instance=\"$host\", job=\"$job\", device!=\"lo\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}