---

rndc_key: '{ algorithm hmac-md5; secret "GrtiE9kz16GK+OKKU/qJvQ==";}'

master_dns: 192.168.50.10
master_dns_name: ns01

slave_dns: 192.168.50.11
slave_dns_name: ns02

client1: 192.168.50.15
client1_dns_name: web1
client1_newdns_name: www
client1_key: '{ algorithm hmac-sha256; secret "IQg171Ht4mdGYcjjYKhI9gSc1fhoxzHZB+h2NMtyZWY="; }'


client2: 192.168.50.16
client2_dns_name: web2
client2_newdns_name: www
client2_key: '{ algorithm hmac-sha256; secret "m7r7SpZ9KBcA4kOl1JHQQnUiIlpQA1IJ9xkBHwdRAHc="; }'