---

- name: Common tasks for bind server
  ansible.builtin.include_role:
    name: bind-common
   
- name: Copy named.conf
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640

- name: Ensure named is running and enabled
  ansible.builtin.service:
    name: named
    state: restarted
    enabled: yes    

